### ISSUE TITLE
UnknownError: <Response [200]>

### ISSUE THREAD

**Issue by pannous** [WatchBeam/beam-client-python#3]
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    chat.authenticate(config.CHANNEL)
  File "/beam-client-python/chatty/connection.py", line 80, in authenticate
    self._log_into_beam()
  File "/beam-client-python/chatty/connection.py", line 54, in _log_into_beam
    raise UnknownError(login_response)
chatty.errors.UnknownError: <Response [200]>

**Comment by Innectic** [comment]
The python example is currently super broken.

**Comment by XCanG** [comment]
Same error.

**Comment by 2Cubed** [comment]
Should be fixed now, thanks to #4. :smile:

**Comment by 200sc** [comment]
This same error is now being mislogged [here](https://github.com/WatchBeam/beam-client-python/blob/master/chatty/connection.py#L53).
The line should log the chat_response, not the login_response
